spring.application.name=PropertyPlatfrorm

<<<<<<< HEAD
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=${MONGO_DB_NAME}

jwt.secret=${SECRET_KEY}
=======
spring.profiles.active=dev
>>>>>>> 071ce94 (implement user service and registration functionalities)
