spring.application.name=PropertyPlatfrorm

jwt.secret=${SECRET_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

#spring.data.mongodb.uri=${MONGO_URL}
#spring.data.mongodb.database=${MONGO_DB_NAME}

spring.mail.host=mail.smtp2go.com
spring.mail.port=587
spring.mail.username=YOUR_SMTP2GO_USERNAME
spring.mail.password=YOUR_SMTP2GO_PASSWORD

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
# SMTP Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
